services:
  pytorch:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c " python3 detect.py"
    # devices:
    # - /dev/video0:/dev/video0
    ports:
      - 8888:8888
    stdin_open: true
    tty: true
